/**
 * File Cleaner module — automatically cleans up leftover files generated by AI
 *
 * Public API:
 *   - AIFileCleaner: the main class
 *   - cleanupAIArtifacts(): quick helper
 *   - removeNote(): remove a section in AI_NOTES.md
 *   - AI_NOTES_FILENAME: name of the notes file
 */

export {
  AIFileCleaner,
  cleanupAIArtifacts,
  removeNote,
  AI_NOTES_FILENAME,
} from './ai_file_cleaner';

export type {
  CleanerOptions,
  CleanupReport,
  CleanupItem,
} from './ai_file_cleaner';